Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.box_version = "1812.01"
  config.vm.hostname = "buildserver"
  config.vm.network :forwarded_port, guest: 80, host: 5555
  config.vm.network :forwarded_port, guest:8080, host:8080

  config.vm.provision "ansible_local" do |jenkins|
   jenkins.playbook = "deploy_jenkins.yml"
  end
end
